### ISSUE TITLE
购买 / 续费舰长不出现在礼物提示中

### ISSUE THREAD

**Issue by RuioWolf** [Tsuk1ko/bilibili-live-chat#11]
![image](https://user-images.githubusercontent.com/15277799/115997639-5c4a7c80-a5d3-11eb-9f8c-bb507a2ac307.png)

这是 bug 还是 feature, 还是b站又改 API 了, 因为 copyliu 的弹幕姬也没统计到舰长的数据。。

**Comment by Yuiffy** [comment]
同求

**Comment by Tsuk1ko** [comment]
已合入
