### ISSUE TITLE
可以添加一个弹幕转语音的功能

### ISSUE THREAD

**Issue by xingxing2008** [Tsuk1ko/bilibili-live-chat#12]
可以添加一个弹幕转语音的功能
就chrome自带的speak就可以了，
（不过似乎chrome对speak接口就做了更改=.=
我按照我的需求改了点的代码，你看看能不能添加这个功能awa

**Comment by Tsuk1ko** [comment]
但 obs 内置浏览器不能播放声音……

**Comment by xingxing2008** [comment]
（emmmm.....我知道，我也试过用speak，obs好像不当这个为声音源，obs没有监听到这一块的声音
而且新版的chrome对speak做了更改，好像有了限制
我现在直播的时候用的是obs监听edge浏览器的声音+obs浏览器

**Comment by Tsuk1ko** [comment]
你说的限制我不清楚，我只知道这个 api 是可以朗读的

https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesis/speaking

如果需要加转语音的功能得考虑很多东西，比如语速、频率、间隔等等，这些都得提供设置，很麻烦，使用率也低，我不倾向于在我这个项目中添加

有需要的话可能自己写个油猴脚本作为插件更实在一些

**Comment by xingxing2008** [comment]
确实
