### ISSUE TITLE
建议：新增显示人气和收藏数

### ISSUE THREAD

**Issue by JackHSC** [Tsuk1ko/bilibili-live-chat#2]
大佬，您好
是这样的。。。。我是吧它当成一个弹幕显示用的，可以在手机的的浏览器中打开，从而达到一个迷你副屏的作用的（因为全屏游戏看不到弹幕和人气之类的），目前已经炒鸡棒了，如何能放个人气和收藏在第一行持续显示就好了（当然也可以做成可关的，方便一些人作为弹幕展示器）。

**Comment by Tsuk1ko** [comment]
这样的话不是直接在手机上打开自己直播间最好吗，我在有副屏以前也是这么干的😂

**Comment by JackHSC** [comment]
好吧你说的好像有点道理（摸头



---原始邮件---
发件人: "神代綺凜"<notifications@github.com&gt;
发送时间: 2019年11月1日(星期五) 晚上7:47
收件人: "Tsuk1ko/bilibili-live-chat"<bilibili-live-chat@noreply.github.com&gt;;
抄送: "JackHSC"<Jack_huangshancheng@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [Tsuk1ko/bilibili-live-chat] 建议：新增显示人气和收藏数 (#2)



这样的话不是直接在手机上打开自己直播间最好吗，我在有副屏以前也是这么干的😂
