### ISSUE TITLE
一个可有可无的issue：cdn.jsdelivr国内访问困难，这导致设置页面的bootstrap样式无法加载

### ISSUE THREAD

**Issue by No5972** [Tsuk1ko/bilibili-live-chat#23]
建议考虑将设置页面的bootstrap地址更换unpkg或者fastly.jsdelivr的地址。这个组件绝大部分都是国内在用的吧。
![](https://img-blog.csdnimg.cn/87309bf722ab4ee8b100473ddb72d2a4.png)
95个节点只有5个能打开
![](https://img-blog.csdnimg.cn/5ad6988a44ee451583bb3e604a13e16b.png)

**Comment by Tsuk1ko** [comment]
确实，cdn.jsdelivr.net 现在貌似在很多地区被 dns 污染了，之前是都能正常解析到 cloudflare 的……

![image](https://user-images.githubusercontent.com/24877906/168780469-b1cc3bff-8200-42fc-893a-a7ae996f4bd0.png)

**Comment by Tsuk1ko** [comment]
发现可以用 code.bdstatic.com

https://v2ex.com/t/521411
