### ISSUE TITLE
获取房间信息失败

### ISSUE THREAD

**Issue by hekatech** [Tsuk1ko/bilibili-live-chat#24]
Access to fetch at 'https://json2jsonp.com/?callback=_&url=https%3A%2F%2Fapi.live.bilibili.com%2Froom_ex%2Fv1%2FRoomNews%2Fget%3Froomid%3D23069492' from origin 'https://blc.lolicon.app' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
json2jsonp.com/?callback=_&url=https%3A%2F%2Fapi.live.bilibili.com%2Froom_ex%2Fv1%2FRoomNews%2Fget%3Froomid%3D23069492:1          Failed to load resource: net::ERR_FAILED

**Comment by Tsuk1ko** [comment]
修复了，如果依然获取失败请看

https://github.com/Tsuk1ko/bilibili-live-chat#%E8%8E%B7%E5%8F%96%E6%88%BF%E9%97%B4%E5%A4%B1%E8%B4%A5%E9%94%99%E8%AF%AF
