### ISSUE TITLE
有调整窗体背景颜色的接口就好了

### ISSUE THREAD

**Issue by NekoSola** [Tsuk1ko/bilibili-live-chat#25]
能通过url传参调整web窗体颜色就好了，或者能显示一张窗体背景图就更好了。

**Comment by Tsuk1ko** [comment]
在 obs 里可以自己写 css 控制

**Comment by NekoSola** [comment]
有个使用场景，就是在pc打开一个spa的网页，用来显示弹幕，给主播看。但是这没办法调整背景色。obs能调整背景色但是只能给观众看，主播自己看不到弹幕。虽然可以手动用审查工具改，但是不能保存，用起来比较麻烦。提个feature，能有这个功能就好了。

**Comment by Tsuk1ko** [comment]
浏览器可以用 Stylus 之类的插件加 css

特殊场景的话倒确实可以加一个自定义 css 配置帮你插入

**Comment by NekoSola** [comment]
> 浏览器可以用 Stylus 之类的插件加 css
> 
> 特殊场景的话倒确实可以加一个自定义 css 配置帮你插入

我的使用场景可能不多见，我用linux的webapp-manager (https://github.com/linuxmint/webapp-manager) 软件把一个网页生成一个单独的app打开。但是这个软件不支持插件，没办法调整页面css，只能打开审查元素手写一个。linux下给主播显示弹幕体验最好的方案就是这个了。win好像也能把独立网页生成一个spa放桌面上，打开之后就像一个软件一样。

**Comment by Tsuk1ko** [comment]
🤔我加上pwa的能力也可以，这样应该不需要专门套壳，还能用浏览器插件
