### ISSUE TITLE
昵称姓名变为首字+***

### ISSUE THREAD

**Issue by hhhhddh** [Tsuk1ko/bilibili-live-chat#26]
近期使用的时候发现大部分观众昵称显示变为首字+三个星号，如清风会变成清***，请问这是什么问题

**Comment by skyatgit** [comment]
@hhhhddh bilibili-live-ws那边的问题，因为B站最近更新了ws认证的机制

**Comment by Tsuk1ko** [comment]
看了下好像新版提供了解决方法，我一会更新一下

**Comment by hhhhddh** [comment]
感谢
