### ISSUE TITLE
头像获取有问题，可能也是bilibili-live-ws那边的问题？

### ISSUE THREAD

**Issue by skyatgit** [Tsuk1ko/bilibili-live-chat#27]
![image](https://github.com/Tsuk1ko/bilibili-live-chat/assets/42607334/8c8cbc2a-35bc-4bac-adec-2c4bb7531c99)

**Comment by Tsuk1ko** [comment]
跟 live ws 无关，晚点看看

**Comment by Tsuk1ko** [comment]
正常用的话没问题，是不是用的官方API，看看 console 里面是不是有报 412 的 error，是的话就是频率过高被B站拉黑了

![image](https://github.com/Tsuk1ko/bilibili-live-chat/assets/24877906/471666de-0e0d-4e9b-8ed9-3142eb0eace4)

![image](https://github.com/Tsuk1ko/bilibili-live-chat/assets/24877906/7e4c02c9-2a28-4737-a177-af1ee44cc7e9)

**Comment by skyatgit** [comment]
没有看到412，会报一个429错误
![image](https://github.com/Tsuk1ko/bilibili-live-chat/assets/42607334/6f1897cc-b4ac-4586-83ed-710c698292ed)
