### ISSUE TITLE
发送弹幕功能好实现吗

### ISSUE THREAD

**Issue by NekoSola** [Tsuk1ko/bilibili-live-chat#28]
linux平台没有弹幕姬，目前重度依赖这个项目当弹幕姬用。没有发弹幕还是不太方便。好实现的话有发弹幕的开关就好了。打开的时候弹幕姬底下出现一个输入框，能输入弹幕发出去。

**Comment by Tsuk1ko** [comment]
目前不考虑，发送弹幕肯定绕不开登录鉴权等，和这个项目的初衷及使用场景都不太符合

目前建议还是直接打开自己的直播间当弹幕姬……
