### ISSUE TITLE
获取房间信息失败

### ISSUE THREAD

**Issue by kidmaomao** [Tsuk1ko/bilibili-live-chat#29]
从前天开始打开网页后会显示获取房间信息失败，不知道是不是需要更新什么~
不知道还有没有可能继续维护，先谢谢了！

**Comment by Tsuk1ko** [comment]
![image](https://github.com/Tsuk1ko/bilibili-live-chat/assets/24877906/81646963-bbff-4798-8c78-415ff5c29d46)
