### ISSUE TITLE
普通模式加cookie会一直断开

### ISSUE THREAD

**Issue by cfandora** [Tsuk1ko/bilibili-live-chat#31]
![image](https://github.com/Tsuk1ko/bilibili-live-chat/assets/26035787/fe585fe5-96be-432d-8822-a0146f39cf51)

因为认证还没下来就先试试普通模式，加上cookie后不管开不开跨域都一直提示已断开
不加cookie能正常连接

**Comment by Tsuk1ko** [comment]
修复了，之前开发的时候把房号写死了忘了改回来（

**Comment by bsdayo** [comment]
仍然能触发（
填 Cookie 就连接已断开，没填就能连上
参数只填了直播间号和 Cookie，普通模式
Cookie 是从 live.bilibili.com 的 `document.cookie` 获取的
~难道是姿势不对~

**Comment by Tsuk1ko** [comment]
> 仍然能触发（ 填 Cookie 就连接已断开，没填就能连上 参数只填了直播间号和 Cookie，普通模式 Cookie 是从 live.bilibili.com 的 `document.cookie` 获取的 ~难道是姿势不对~

从 devtools 的 network 里面找个请求拿

`document.cookie` 无法获取 HttpOnly 的 cookie，其中 SESSDATA 貌似正好是必须的

![image](https://github.com/Tsuk1ko/bilibili-live-chat/assets/24877906/096ade38-bd99-406b-8d92-7dbd598603dd)

**Comment by bsdayo** [comment]
> > 仍然能触发（ 填 Cookie 就连接已断开，没填就能连上 参数只填了直播间号和 Cookie，普通模式 Cookie 是从 live.bilibili.com 的 `document.cookie` 获取的 ~难道是姿势不对~
> 
> 从 devtools 的 network 里面找个请求拿
> 
> `document.cookie` 无法获取 HttpOnly 的 cookie，其中 SESSDATA 貌似正好是必须的
> 
> ![image](https://private-user-images.githubusercontent.com/24877906/290062162-096ade38-bd99-406b-8d92-7dbd598603dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0Mzc2MzIsIm5iZiI6MTcwMjQzNzMzMiwicGF0aCI6Ii8yNDg3NzkwNi8yOTAwNjIxNjItMDk2YWRlMzgtYmQ5OS00MDZiLThkOTItN2RiZDU5ODYwM2RkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDAzMTUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4M2U0NjdhMjU4Zjk0OWIwMjlhNDIzYTdjNGI1OWZhMWVmMTM4NTNlNWVjMTAxMzFiODdhNmE0NWE2ODI2MTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MnBP3XuNS3cXgMX92PmM21menc_UVqu82_wrGzffcvI)

原来是这样，感谢
