### ISSUE TITLE
开发平台模式下无法获取弹幕页链接

### ISSUE THREAD

**Issue by Avimitin** [Tsuk1ko/bilibili-live-chat#32]
选择了开发模式并填写信息之后，复制链接的按钮一直是灰色无法框选状态。但是能确认信息都正确填上了。

![image](https://github.com/Tsuk1ko/bilibili-live-chat/assets/30021675/281a10f8-f6f3-4c2e-9993-3b194a001eb3)

**Comment by Tsuk1ko** [comment]
修复了
