### ISSUE TITLE
网页端可以正常实时显示弹幕，但OBS中的浏览器无法显示弹幕

### ISSUE THREAD

**Issue by Hana61** [Tsuk1ko/bilibili-live-chat#33]
我开启了跨域模式，并在chrome与obs的快捷方式中填写了对应的启动项，随后chrome可以正常显示实时弹幕，但obs中的浏览器插件一直不显示任何内容，obs浏览器插件的URL是直接复制链接来的，请问如何解决？

**Comment by Hana61** [comment]
![image](https://github.com/Tsuk1ko/bilibili-live-chat/assets/87906832/f8070ce3-24be-44c8-809a-0a6442e368af)

**Comment by Tsuk1ko** [comment]
obs 中浏览器没显示什么报错吗

需要注意如果你用开放平台连接的话，不能多开，使用 obs 前先关掉 chrome 里打开的

**Comment by Hana61** [comment]
obs中没有错误提示，就完全没有任何显示内容，我是使用开放平台连接的，没有报错，我尝试一下关掉浏览器是否奏效

**Comment by Hana61** [comment]
我关掉了chrome里面的窗口，obs依然没有反应，obs浏览器插件设置如下
![image](https://github.com/Tsuk1ko/bilibili-live-chat/assets/87906832/ced8475e-c355-42a2-b3c0-661527264c06)

**Comment by Tsuk1ko** [comment]
那就不知道了……

会不会是网络问题，而你 chrome 是有代理的

**Comment by Hana61** [comment]
会和我挂梯子有关吗？我尝试一下

**Comment by Hana61** [comment]
我关掉梯子依然不行，如何在obs里访问主页？我尝试添加了三个浏览器插件，obs主页可以加载，B站可以加载，google加载不了
![image](https://github.com/Tsuk1ko/bilibili-live-chat/assets/87906832/de417870-1285-4d21-b59e-989d1395fdde)

**Comment by Tsuk1ko** [comment]
我指的是 https://blc.lolicon.app

**Comment by Hana61** [comment]
闪了一下白的之后就什么都不显示了
![image](https://github.com/Tsuk1ko/bilibili-live-chat/assets/87906832/4f2e321f-3b00-4aa3-9c94-cf1385244947)

**Comment by Tsuk1ko** [comment]
那估计还是网络问题 🤔

**Comment by Hana61** [comment]
![image](https://github.com/Tsuk1ko/bilibili-live-chat/assets/87906832/3de4181b-d179-45a6-a59d-bc429cdfb0da)

**Comment by Hana61** [comment]
emmm，确实，我在北京，但是我梯子常开，也许和我挂梯子有关系？我尝试一下完全关掉梯子，重启电脑，再进行尝试，之后给您反馈，谢谢您的解答
