### ISSUE TITLE
不开启跨域模式下，使用开放平台，开启失败

### ISSUE THREAD

**Issue by Leghtin** [Tsuk1ko/bilibili-live-chat#34]
![image](https://github.com/Tsuk1ko/bilibili-live-chat/assets/17336721/48bf5073-bd1c-4fba-b09d-df56a8e2bac6)
提示如上

**Comment by Tsuk1ko** [comment]
这玩意主流浏览器应该很早就支持了，你用的是什么浏览器？

![image](https://github.com/Tsuk1ko/bilibili-live-chat/assets/24877906/14ca0fd1-ed3c-416e-aa2c-1fe3f6729acc)

**Comment by Leghtin** [comment]
EDGE浏览器，版本的话 120.0.2210.91

**Comment by Leghtin** [comment]
> 这玩意主流浏览器应该很早就支持了，你用的是什么浏览器，什么版本？
> 
> ![image](https://private-user-images.githubusercontent.com/24877906/293854700-14ca0fd1-ed3c-416e-aa2c-1fe3f6729acc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNjk0NDYsIm5iZiI6MTcwNDI2OTE0NiwicGF0aCI6Ii8yNDg3NzkwNi8yOTM4NTQ3MDAtMTRjYTBmZDEtZWQzYy00MTZlLWFhMmMtMWZlM2Y2NzI5YWNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDA4MDU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmZjdhNzUwNDcwZTRmYjI4YTkxZDU2MTM2NjE3NGU3ZDZmZDRlNzk1MWZhOWQ0YzNkMDJhMDhhMmQyZWE4ZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fYRigYE_krWZstHOL9C4hXh96xdZEhTOfTkLg-lIj28)

刚刚从项目的[blc.lolicon.app](https://blc.lolicon.app/)链接进入可以完成弹幕显示，但是从NGA FF14模块进入的http://bilichat.centralteam.cn/无法完成开启

**Comment by Tsuk1ko** [comment]
那破案了，Web Crypto API 只能在安全上下文中使用，即要求 https，这个链接好像只有 http

http://bilichat.centralteam.cn/ 不是我的，应该是其他人部署了本开源项目，你可以向 nga 贴主反馈
