### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'importKey')

### ISSUE THREAD

**Issue by MisakaAI** [Tsuk1ko/bilibili-live-chat#40]
环境相关：
nodejs v20.12.2
yarn v1.22.22

`yarn install && yarn build` 之后，将 `dist` 下的内容复制到 `/var/www/html` 中，服务器使用的是`nginx`。

然后使用的时候，会收到错误提示：

```
开放平台开启失败
TypeError: Cannot read properties of undefined (reading 'importKey')
```

**Comment by Tsuk1ko** [comment]
![image](https://github.com/Tsuk1ko/bilibili-live-chat/assets/24877906/3f805b2a-6583-4f8b-aaa3-40c122b66fc8)

不至于不支持这个吧

**Comment by Tsuk1ko** [comment]
你需要 https，web crypto 要在安全上下文中才能使用，你搞个自签证书吧

**Comment by MisakaAI** [comment]
好的，感谢~

**Comment by MisakaAI** [comment]
使用https之后，错误又变成了……OTL

开放平台开启失败
SyntaxError: Unexpected end of JSON input

**Comment by Tsuk1ko** [comment]
自己部署的话只能用跨域模式，我的那些反代服务只允许我自己部署的域名使用

如果已经是跨域模式，看一下 devtools 的 network 请求出了什么问题
