### ISSUE TITLE
网页链接弹幕会显示，但是在OBS客户端添加浏览器源后，弹幕并不会显示

### ISSUE THREAD

**Issue by MikoLee2333** [Tsuk1ko/bilibili-live-chat#6]
网页链接弹幕会显示，但是在OBS客户端添加浏览器源后，弹幕并不会显示
```
https://bilivechat.moe.best/livechat.html#room=7410039&face=direct&display=bottom&giftComb=5000&speed=11&stay=360000
```
***********************************************************************************
浏览器界面
![image](https://user-images.githubusercontent.com/43770943/78376294-af384700-7600-11ea-8900-5993a23f472d.png)
OBS界面
![image](https://user-images.githubusercontent.com/43770943/78376374-cd05ac00-7600-11ea-87bb-516f4c7db8f5.png)
url设置界面
![image](https://user-images.githubusercontent.com/43770943/78376434-e9a1e400-7600-11ea-8d72-9fec6beb0f67.png)

**Comment by MikoLee2333** [comment]
并且本地客户端也可以获取到头像的信息，但是就是不显示在OBS的捕获页面中
![image](https://user-images.githubusercontent.com/43770943/78379028-5d91bb80-7604-11ea-8eab-1e9679460dcd.png)

**Comment by Tsuk1ko** [comment]
明日再验证，今日B站直播掐了

**Comment by Tsuk1ko** [comment]
未能复现，你显示头像使用跨域方式，OBS 有加`--disable-web-security`参数？

![image](https://user-images.githubusercontent.com/24877906/78467037-2eca3100-773b-11ea-95c7-7045b779c89d.png)

**Comment by MikoLee2333** [comment]
后面我换成本地的方式，一样没办法在obs显示弹幕



---原始邮件---
发件人: "神代綺凜"<notifications@github.com&gt;
发送时间: 2020年4月5日(周日) 中午12:46
收件人: "Tsuk1ko/bilibili-live-chat"<bilibili-live-chat@noreply.github.com&gt;;
抄送: "MikoLee"<1737416093@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [Tsuk1ko/bilibili-live-chat] 网页链接弹幕会显示，但是在OBS客户端添加浏览器源后，弹幕并不会显示 (#6)




 
未能复现，你显示头像使用跨域方式，OBS 有加--disable-web-security参数？

**Comment by MikoLee2333** [comment]
问题解决了，弹幕能在obs捕捉到了，非常感谢！



---原始邮件---
发件人: "神代綺凜"<notifications@github.com&gt;
发送时间: 2020年4月5日(周日) 中午12:46
收件人: "Tsuk1ko/bilibili-live-chat"<bilibili-live-chat@noreply.github.com&gt;;
抄送: "MikoLee"<1737416093@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [Tsuk1ko/bilibili-live-chat] 网页链接弹幕会显示，但是在OBS客户端添加浏览器源后，弹幕并不会显示 (#6)




 
未能复现，你显示头像使用跨域方式，OBS 有加--disable-web-security参数？

**Comment by Tsuk1ko** [comment]
![image](https://user-images.githubusercontent.com/24877906/78467943-d861f000-7744-11ea-8a57-0d4909e05f34.png)
