### ISSUE TITLE
现无法获取弹幕

### ISSUE THREAD

**Issue by kidmaomao** [Tsuk1ko/bilibili-live-chat#7]
今天可能b站做了变更，现在无法正常读取弹幕信息了~

还请大佬花时间更新！~

**Comment by Tsuk1ko** [comment]
读取弹幕是依靠 [std4453/bilibili-danmaku-client](https://github.com/std4453/bilibili-danmaku-client) 的，因此需要向该项目提出 issue

不过看上去原作者已经没有在维护了，我也不清楚自己有没有能力修复它，有时间我研究下吧

**Comment by MikoLee2333** [comment]
我也是今天发现这个问题

**Comment by Tsuk1ko** [comment]
看起来像是新版本的直播弹幕传输协议多加了一层加密，反正我不会搞（摊手

**Comment by MikoLee2333** [comment]
我这里还有小葫芦的弹幕助手，他们已经解决这个问题了，可惜我不会反编译软件，不然可以看看怎么解决的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"神代綺凜"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月11日(星期六) 中午1:12
收件人:&nbsp;"Tsuk1ko/bilibili-live-chat"<bilibili-live-chat@noreply.github.com&gt;;
抄送:&nbsp;"1737416093"<1737416093@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Tsuk1ko/bilibili-live-chat] 现无法获取弹幕 (#7)





 
看起来像是新版本的直播弹幕传输协议多加了一层加密，反正我不会搞（摊手

**Comment by Tsuk1ko** [comment]
看到一个正常运行的项目使用的是新版协议，吃完饭看看代码

**Comment by kidmaomao** [comment]
大佬加油！

**Comment by MikoLee2333** [comment]
不，我是five



---原始邮件---
发件人: "kidmaomao"<notifications@github.com&gt;
发送时间: 2020年4月11日(周六) 下午3:15
收件人: "Tsuk1ko/bilibili-live-chat"<bilibili-live-chat@noreply.github.com&gt;;
抄送: "MikoLee"<1737416093@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [Tsuk1ko/bilibili-live-chat] 现无法获取弹幕 (#7)




 
大佬加油！

**Comment by Tsuk1ko** [comment]
更新：已经看懂怎么回事了……能解析出来了，我看看怎么改代码比较好

**Comment by MikoLee2333** [comment]
大佬牛批




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"神代綺凜"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月11日(星期六) 下午3:47
收件人:&nbsp;"Tsuk1ko/bilibili-live-chat"<bilibili-live-chat@noreply.github.com&gt;;
抄送:&nbsp;"1737416093"<1737416093@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Tsuk1ko/bilibili-live-chat] 现无法获取弹幕 (#7)





 
更新：已经看懂怎么回事了……能解析出来了，我看看怎么改代码比较好

**Comment by Tsuk1ko** [comment]
整好了，现在可以用了

**Comment by kidmaomao** [comment]
收到！已测试，完全OK，感谢大佬~

**Comment by MikoLee2333** [comment]
我试试



---原始邮件---
发件人: "神代綺凜"<notifications@github.com&gt;
发送时间: 2020年4月11日(周六) 下午5:55
收件人: "Tsuk1ko/bilibili-live-chat"<bilibili-live-chat@noreply.github.com&gt;;
抄送: "MikoLee"<1737416093@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [Tsuk1ko/bilibili-live-chat] 现无法获取弹幕 (#7)




 
整好了，现在可以用了

**Comment by skull1987** [comment]
大佬厉害！！已经可以使用了！！
