### ISSUE TITLE
弹幕丢失严重

### ISSUE THREAD

**Issue by daofeng2015** [Tsuk1ko/bilibili-live-chat#8]
弹幕信息在热度高的房间会出现漏弹幕的情况,还有最好加个短号房间id转换为真正id的api就可以了,协议部分参考 [这里](https://www.bilibili.com/video/BV1r4411P7W8)

**Comment by Tsuk1ko** [comment]
漏弹幕你得找 [std4453/bilibili-danmaku-client](https://github.com/std4453/bilibili-danmaku-client)

短号的等以后我重构的时候顺便加上

**Comment by daofeng2015** [comment]
> 漏弹幕你得找 [std4453/bilibili-danmaku-client](https://github.com/std4453/bilibili-danmaku-client)
> 
> 短号的等以后我重构的时候顺便加上

作者已经完全不管那个项目了....大神更新下...

**Comment by Tsuk1ko** [comment]
所以我也很无奈啊……这就是直接 ws 连的官方弹幕服务器，你说会丢弹幕我也没有头绪，还能怎么改呢

**Comment by daofeng2015** [comment]
> 所以我也很无奈啊……这就是直接 ws 连的官方弹幕服务器，你说会丢弹幕我也没有头绪，还能怎么改呢

就是有些弹幕是压缩的.你得想办法zlib解开,里面是二个弹幕消息

**Comment by Tsuk1ko** [comment]
解了的，上个月就是因为旧版弹幕协议也强制 zlib 了导致用不了，我才专门去看的源码然后改的

https://github.com/Tsuk1ko/bilibili-danmaku-client/commit/f9ee8c2559b6299fe449685ce6a27823aeb95ed0

**Comment by daofeng2015** [comment]
> 解了的，上个月就是因为旧版弹幕协议也强制 zlib 了导致用不了，我才专门去看的源码然后改的
> 
> [Tsuk1ko/bilibili-danmaku-client@f9ee8c2](https://github.com/Tsuk1ko/bilibili-danmaku-client/commit/f9ee8c2559b6299fe449685ce6a27823aeb95ed0)
那就奇怪了...b站弹幕协议难道又更新了吗?

**Comment by Tsuk1ko** [comment]
要不就是全面 v2 协议相比 v1 有加成，但目前现有的 v2 协议的客户端基本都是 python 写的，没有 js 实现，我也懒得研究重写，毕竟我自己没有这么大需求

**Comment by daofeng2015** [comment]
> 要不就是全面 v2 协议相比 v1 有加成，但目前现有的 v2 协议的客户端基本都是 python 写的，没有 js 实现，我也懒得研究重写，毕竟我自己没有这么大需求

我在逛专栏的时候发现了b站官方的obs弹幕姬(???,你可以断点调试一下

**Comment by daofeng2015** [comment]
> 要不就是全面 v2 协议相比 v1 有加成，但目前现有的 v2 协议的客户端基本都是 python 写的，没有 js 实现，我也懒得研究重写，毕竟我自己没有这么大需求

http://link.bilibili.com/ctool/vtuber/

**Comment by Tsuk1ko** [comment]
这没用，js 压缩过的又看不懂

**Comment by daofeng2015** [comment]
> 这没用，js 压缩过的又看不懂

找到了js版本.改的有点多..有点难的理解

**Comment by daofeng2015** [comment]
https://github.com/hling51325/bilibili-live-danmaku/blob/master/src/service/bilibili-live-ws.js

**Comment by Tsuk1ko** [comment]
看起来还行，不过貌似没有解析礼物……

https://github.com/hling51325/bilibili-live-danmaku/blob/616a04aed037bb219d1308107b3e452ee6511cb7/src/service/bilibili-live-ws.js#L259-L261

**Comment by daofeng2015** [comment]
> 看起来还行，不过貌似没有解析礼物……
> 
> https://github.com/hling51325/bilibili-live-danmaku/blob/616a04aed037bb219d1308107b3e452ee6511cb7/src/service/bilibili-live-ws.js#L259-L261

这个更加详细了... https://github.com/kooritea/bilibili-ws/blob/master/BilibiliWebSocket.js

**Comment by daofeng2015** [comment]
> 看起来还行，不过貌似没有解析礼物……
> 
> https://github.com/hling51325/bilibili-live-danmaku/blob/616a04aed037bb219d1308107b3e452ee6511cb7/src/service/bilibili-live-ws.js#L259-L261

我谷歌了下 发现很多博主更新了.....放一个参考下  http://blog.pppane.com/index.php/archives/24/

**Comment by daofeng2015** [comment]
https://github.com/lovelyyoshino/Bilibili-Live-API/blob/master/API.WebSocket.md  大神提炼出来所有参数......太6了

**Comment by Tsuk1ko** [comment]
我觉得还是用这个吧 https://github.com/simon300000/bilibili-live-ws

**Comment by daofeng2015** [comment]
![QQ截图20200604211040](https://user-images.githubusercontent.com/14891398/83760706-e6ca7a80-a6a7-11ea-9ac0-359d651ef342.png)
改了一大半的代码 实现了这样的功能

**Comment by Tsuk1ko** [comment]
我重构完了，顺便也加了你这个分开显示的功能，有兴趣的话可以体验一下

https://blc.lolicon.app/
