### ISSUE TITLE
请问可以添加如何完全在本地部署的说明吗？

### ISSUE THREAD

**Issue by lolisound** [Tsuk1ko/bilibili-live-chat#9]
有时候会接收不到弹幕，不知道是不是服务器的问题…

**Comment by Tsuk1ko** [comment]
这玩意是纯前端的，直接在网页中连接B站弹幕服务器

如果担心 GitHub Pages 静态资源加载不畅的话直接 clone 下来，浏览器打开 `docs` 文件夹内的 `index.html` 就行

**Comment by lolisound** [comment]
谢谢＜（＾－＾）＞

神代綺凜 <notifications@github.com> 于2020年6月6日周六 下午8:01写道：
